package com.mybatis.demo.demo.dao;

import com.mybatis.demo.demo.model.Admin;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    Admin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_admin
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int updateByPrimaryKey(Admin record);

    Admin selectByNameAndPsd(Admin admin);
}