package com.mybatis.demo.demo.dao;

import com.mybatis.demo.demo.model.Feedback;

public interface FeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int deleteByPrimaryKey(Integer feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int insert(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int insertSelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    Feedback selectByPrimaryKey(Integer feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int updateByPrimaryKeySelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_feedback
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int updateByPrimaryKey(Feedback record);
}