package com.mybatis.demo.demo.dao;

import com.mybatis.demo.demo.model.Student;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;


@Mapper
@Repository
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    Student selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    int updateByPrimaryKey(Student record);

    Student selectByUserNameAndPassword(Student student);
}