package com.mybatis.demo.demo.model;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.admin_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.admin_name
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin.admin_password
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String adminPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.admin_id
     *
     * @return the value of tb_admin.admin_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.admin_id
     *
     * @param adminId the value for tb_admin.admin_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.admin_name
     *
     * @return the value of tb_admin.admin_name
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.admin_name
     *
     * @param adminName the value for tb_admin.admin_name
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin.admin_password
     *
     * @return the value of tb_admin.admin_password
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin.admin_password
     *
     * @param adminPassword the value for tb_admin.admin_password
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }
}