package com.mybatis.demo.demo.model;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback.feedback_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer feedbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback.order_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback.feedback_score
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer feedbackScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback.feedback_who
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer feedbackWho;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_feedback.feedback_words
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String feedbackWords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback.feedback_id
     *
     * @return the value of tb_feedback.feedback_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback.feedback_id
     *
     * @param feedbackId the value for tb_feedback.feedback_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback.order_id
     *
     * @return the value of tb_feedback.order_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback.order_id
     *
     * @param orderId the value for tb_feedback.order_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback.feedback_score
     *
     * @return the value of tb_feedback.feedback_score
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getFeedbackScore() {
        return feedbackScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback.feedback_score
     *
     * @param feedbackScore the value for tb_feedback.feedback_score
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setFeedbackScore(Integer feedbackScore) {
        this.feedbackScore = feedbackScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback.feedback_who
     *
     * @return the value of tb_feedback.feedback_who
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getFeedbackWho() {
        return feedbackWho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback.feedback_who
     *
     * @param feedbackWho the value for tb_feedback.feedback_who
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setFeedbackWho(Integer feedbackWho) {
        this.feedbackWho = feedbackWho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_feedback.feedback_words
     *
     * @return the value of tb_feedback.feedback_words
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getFeedbackWords() {
        return feedbackWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_feedback.feedback_words
     *
     * @param feedbackWords the value for tb_feedback.feedback_words
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setFeedbackWords(String feedbackWords) {
        this.feedbackWords = feedbackWords;
    }
}