package com.mybatis.demo.demo.model;

public class OrderList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderlist.order_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderlist.student_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderlist.teacher_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderlist.order_state
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer orderState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderlist.order_id
     *
     * @return the value of tb_orderlist.order_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderlist.order_id
     *
     * @param orderId the value for tb_orderlist.order_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderlist.student_id
     *
     * @return the value of tb_orderlist.student_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderlist.student_id
     *
     * @param studentId the value for tb_orderlist.student_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderlist.teacher_id
     *
     * @return the value of tb_orderlist.teacher_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderlist.teacher_id
     *
     * @param teacherId the value for tb_orderlist.teacher_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderlist.order_state
     *
     * @return the value of tb_orderlist.order_state
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderlist.order_state
     *
     * @param orderState the value for tb_orderlist.order_state
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderState(Integer orderState) {
        this.orderState = orderState;
    }
}