package com.mybatis.demo.demo.model;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderitem.order_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderitem.student_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderitem.order_grade
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String orderGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderitem.order_subject
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String orderSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderitem.order_pay
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer orderPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderitem.order_place
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String orderPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderitem.order_state
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String orderState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderitem.order_time
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Double orderTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderitem.order_id
     *
     * @return the value of tb_orderitem.order_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderitem.order_id
     *
     * @param orderId the value for tb_orderitem.order_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderitem.student_id
     *
     * @return the value of tb_orderitem.student_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderitem.student_id
     *
     * @param studentId the value for tb_orderitem.student_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderitem.order_grade
     *
     * @return the value of tb_orderitem.order_grade
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getOrderGrade() {
        return orderGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderitem.order_grade
     *
     * @param orderGrade the value for tb_orderitem.order_grade
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderGrade(String orderGrade) {
        this.orderGrade = orderGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderitem.order_subject
     *
     * @return the value of tb_orderitem.order_subject
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getOrderSubject() {
        return orderSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderitem.order_subject
     *
     * @param orderSubject the value for tb_orderitem.order_subject
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderSubject(String orderSubject) {
        this.orderSubject = orderSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderitem.order_pay
     *
     * @return the value of tb_orderitem.order_pay
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getOrderPay() {
        return orderPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderitem.order_pay
     *
     * @param orderPay the value for tb_orderitem.order_pay
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderPay(Integer orderPay) {
        this.orderPay = orderPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderitem.order_place
     *
     * @return the value of tb_orderitem.order_place
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getOrderPlace() {
        return orderPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderitem.order_place
     *
     * @param orderPlace the value for tb_orderitem.order_place
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderPlace(String orderPlace) {
        this.orderPlace = orderPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderitem.order_state
     *
     * @return the value of tb_orderitem.order_state
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderitem.order_state
     *
     * @param orderState the value for tb_orderitem.order_state
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderitem.order_time
     *
     * @return the value of tb_orderitem.order_time
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Double getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderitem.order_time
     *
     * @param orderTime the value for tb_orderitem.order_time
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setOrderTime(Double orderTime) {
        this.orderTime = orderTime;
    }
}