package com.mybatis.demo.demo.model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.student_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.student_name
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.student_password
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String studentPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.student_phone
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String studentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.student_email
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String studentEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.student_score
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Double studentScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.student_id
     *
     * @return the value of tb_student.student_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.student_id
     *
     * @param studentId the value for tb_student.student_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.student_name
     *
     * @return the value of tb_student.student_name
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.student_name
     *
     * @param studentName the value for tb_student.student_name
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.student_password
     *
     * @return the value of tb_student.student_password
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getStudentPassword() {
        return studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.student_password
     *
     * @param studentPassword the value for tb_student.student_password
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setStudentPassword(String studentPassword) {
        this.studentPassword = studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.student_phone
     *
     * @return the value of tb_student.student_phone
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getStudentPhone() {
        return studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.student_phone
     *
     * @param studentPhone the value for tb_student.student_phone
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.student_email
     *
     * @return the value of tb_student.student_email
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getStudentEmail() {
        return studentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.student_email
     *
     * @param studentEmail the value for tb_student.student_email
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.student_score
     *
     * @return the value of tb_student.student_score
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Double getStudentScore() {
        return studentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.student_score
     *
     * @param studentScore the value for tb_student.student_score
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setStudentScore(Double studentScore) {
        this.studentScore = studentScore;
    }
}