package com.mybatis.demo.demo.model;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacher_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacher_name
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacher_password
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String teacherPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacher_phone
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String teacherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacher_email
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private String teacherEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.teacher_score
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    private Double teacherScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacher_id
     *
     * @return the value of tb_teacher.teacher_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacher_id
     *
     * @param teacherId the value for tb_teacher.teacher_id
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacher_name
     *
     * @return the value of tb_teacher.teacher_name
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacher_name
     *
     * @param teacherName the value for tb_teacher.teacher_name
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacher_password
     *
     * @return the value of tb_teacher.teacher_password
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getTeacherPassword() {
        return teacherPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacher_password
     *
     * @param teacherPassword the value for tb_teacher.teacher_password
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setTeacherPassword(String teacherPassword) {
        this.teacherPassword = teacherPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacher_phone
     *
     * @return the value of tb_teacher.teacher_phone
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getTeacherPhone() {
        return teacherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacher_phone
     *
     * @param teacherPhone the value for tb_teacher.teacher_phone
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setTeacherPhone(String teacherPhone) {
        this.teacherPhone = teacherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacher_email
     *
     * @return the value of tb_teacher.teacher_email
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public String getTeacherEmail() {
        return teacherEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacher_email
     *
     * @param teacherEmail the value for tb_teacher.teacher_email
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setTeacherEmail(String teacherEmail) {
        this.teacherEmail = teacherEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.teacher_score
     *
     * @return the value of tb_teacher.teacher_score
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public Double getTeacherScore() {
        return teacherScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.teacher_score
     *
     * @param teacherScore the value for tb_teacher.teacher_score
     *
     * @mbggenerated Tue Jan 07 21:15:34 CST 2020
     */
    public void setTeacherScore(Double teacherScore) {
        this.teacherScore = teacherScore;
    }
}